### ISSUE TITLE
Implement resourceZendeskTicketFieldRead

### ISSUE THREAD

**Issue by tamccall** [nukosuke/terraform-provider-zendesk#18]
Need to be able to read ticket field resources in order to properly support [resource imports](https://www.terraform.io/docs/import/index.html).

Currently `resourceZendeskTicketFieldRead` is an empty function that just returns nil.

Ask is to make that function actually call the Zendesk API to get the specified resource using its ID.

**Comment by nukosuke** [comment]
ref: #22

**Comment by tamccall** [comment]
going to start working on update and delete as part of this as well
