### ISSUE TITLE
Implement resourceZendeskTicketFormRead

### ISSUE THREAD

**Issue by tamccall** [nukosuke/terraform-provider-zendesk#21]
Need to be able to read ticket form resources in order to properly support [resource imports](https://www.terraform.io/docs/import/index.html).

Currently `resourceZendeskTicketFormRead` is an empty function that just returns nil.

Ask is to make that function actually call the Zendesk API to get the specified resource using its ID.

**Comment by tamccall** [comment]
@nukosuke am i wrong in saying that this will require some client uplift as well? It doesn't seem like we have the ability to call this api to get a specific ticket field. https://developer.zendesk.com/rest_api/docs/support/ticket_fields#show-ticket-field

**Comment by nukosuke** [comment]
@tamccall 

Are you using `dep` to get dependencies?

The version of go-zendesk is locked to v0.0.0 in `Gopkg.{toml,lock}`.
https://github.com/nukosuke/terraform-provider-zendesk/blob/master/Gopkg.toml#L36-L38

I merged https://github.com/nukosuke/go-zendesk/pull/50 and released v0.1.0.
Please change the version to latest (or `master` if you'd like)

**Comment by nukosuke** [comment]
#82 
closing?
