### ISSUE TITLE
Add acceptance tests for all of the v0.0.0 resources

### ISSUE THREAD

**Issue by tamccall** [nukosuke/terraform-provider-zendesk#71]
Add acceptance tests for the following resources

- [x] Ticket Form
- [x] Brands #178 
- [x] Groups #74 
- [x] Attachments #97  
- [x] Triggers #140, #166

**Comment by tamccall** [comment]
Form tests are written but are currently being skipped

**Comment by nukosuke** [comment]
v0.0.0 acc tests have been completed
